image: golang:latest

stages:
  - test
services:
  - mysql:latest
  - name: blacktop/kafka
    alias: kafka


variables:
  KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:9092,INTERNAL://localhost:9093'
  KAFKA_BROKER_ID: '1'
  KAFKA_INTER_BROKER_LISTENER_NAME: 'INTERNAL'
  KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:9092,INTERNAL://0.0.0.0:9093'
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'PLAINTEXT:PLAINTEXT,INTERNAL:PLAINTEXT'
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  KAFKA_CREATE_TOPICS: "test:1:1"

lint:
  stage: test
  script:
    - make vet

unit_test:
  parallel:
    matrix:
      - GO: ["1.20"]
  image:
    name: golang:$GO
  stage: test
  script:
    - make test

